name: Generate ANTLR Regression Reports

on:
  workflow_call:
    inputs:
      patch-branch:
        description: 'The checkstyle patch branch'
        required: true
        type: string
      project-names:
        description: 'Json array of project names for ANTLR diff report generation'
        required: true
        type: string

jobs:
  generate_antlr_regression_report:
    runs-on: ubuntu-latest
    container: checkstyle/jdk-11-groovy-git-mvn:11.0.13__3.0.9__2.25.1__3.6.3
    env:
      MAVEN_OPTS: -Xmx5g
      JAVA_OPTS: -Xmx5g
      CHECKSTYLE_DIRECTORY: checkstyle
      ROOT_DIR: /__w/checkstyle-diff-report-generator/checkstyle-diff-report-generator

      # change for report generation
      PATCH_BRANCH: ${{ inputs.patch-branch }}

    strategy:
      matrix:
        project_name: ${{ fromJson(inputs.project-names) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout Checkstyle
        uses: actions/checkout@v3
        with:
          repository: nrmancuso/checkstyle
          path: checkstyle
          fetch-depth: 0

      - name: Checkout Contribution
        uses: actions/checkout@v3
        with:
          repository: nrmancuso/contribution
          path: contribution

      - name: Build patch-diff-report-tool
        run: |
          cd "${ROOT_DIR}/contribution/patch-diff-report-tool"
          mvn clean install

      - name: Set up local checkstyle repo
        run: |
          cd "${ROOT_DIR}/checkstyle"
          git remote add upstream https://github.com/checkstyle/checkstyle
          git fetch --all
          git checkout master
          git reset --hard upstream/master
          git checkout $PATCH_BRANCH

      - name: Generate report
        env:
          PROJECT: ${{ matrix.project_name }}
          REPORT_REPO_DIR: ${{ env.ROOT_DIR }}/main
        run: ./main/scripts/generate-antlr-regression-report.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: antlr-report-${{ matrix.project_name }}
          path: contribution/checkstyle-tester/reports/diff
          retention-days: 60
          if-no-files-found: error
